### ISSUE TITLE
Wrong documentation for creating organization

### ISSUE THREAD

**Issue by gxvigo** [IBM-Bluemix-Docs/admin#5]
The documentation about creating organization is wrong:
click Manage > Account > Organizations
There's no such a menu.

**Comment by gxvigo** [comment]
I have a trial account, maybe that's the reason I don't have that item in the menu.

**Comment by plindblue** [comment]
I have updated the UI path to reflect the correct path

To manage organizations and spaces, click Manage > Account > Cloud Foundry Orgs.
